### ISSUE TITLE
Broken directory handling

### ISSUE THREAD

**Issue by balopat** [sbdchd/codeowners#13]
The new release 0.2.0 broke the recursive directory handling:

```
from codeowners import CodeOwners

owners = CodeOwners("""**/dir/**/*.* @a""").of("bla/dir/file.txt")
assert owners == [('USERNAME', '@a')], owners
```

This works with the 0.1.2 (rust) version.

**Comment by sbdchd** [comment]
Thanks for the report and test case, sorry about the bug

I think I need to figure out a proper glob implementation

Python's `glob` uses:

https://docs.python.org/3/library/fnmatch.html

But that doesn't have the same behavior required by code owners

The current path -> regex function naively only uses characters at the start and end for matching and escapes everything else.

https://github.com/sbdchd/codeowners/blob/e874f73c9e6949b5aebfb1a9eb6ed0ca67db876b/codeowners/__init__.py#L20-L41

Instead we'll need to escape most of the regex characters in the string and translate `*` and `**` accordingly

**Comment by sbdchd** [comment]
Didn't mean to close this yet since the fix hasn't been released to pypi

**Comment by sbdchd** [comment]
Version 0.2.1 is now on Pypi

Let me know if you have any further issues
