### ISSUE TITLE
Publish wheels for Python 3.8

### ISSUE THREAD

**Issue by martinxsliu** [sbdchd/codeowners#2]
Hi there, currently there are only wheels for Python 3.7 (and 3.6 for linux): https://pypi.org/project/codeowners/#files. Would it be possible to build and publish wheels for Python 3.8 as well (for linux and macosx)?

**Comment by sbdchd** [comment]
totally! I'll look into this after work

**Comment by sbdchd** [comment]
I've added python 3.8 weeks for linux and mac os

Feel free to reopen the wheels don't work as expected

**Comment by martinxsliu** [comment]
Thank you!
