### ISSUE TITLE
Support typing_extensions >= 4

### ISSUE THREAD

**Issue by martinxsliu** [sbdchd/codeowners#29]
Hi there! `typing_extensions`, a dependency of this pkg, has released a v4 version for a few months: https://pypi.org/project/typing-extensions/, but this pkg pins `typing_extensions` to v3. Afaict the v4 update drops support for older Python versions (i.e. py2 and py3.5) and adopts semantic versioning.

We're running into some issues resolving versions between this pkg and the latest versions of other pkgs that have dependencies on `typing_extensions` because of this pin. Could we update the version constraint (or accept a PR to do so)? Since this pkg only uses the `Literal` type, I don't think there would be any problems allowing v4?

**Comment by sbdchd** [comment]
Yeah sounds good!
