### ISSUE TITLE
Single asterisk matches files in subfolders

### ISSUE THREAD

**Issue by pocmo** [sbdchd/codeowners#44]
In this example:

```python
owners = CodeOwners("""
    docs/generator/build.py @octocat
    
    # The `docs/*` pattern will match files like
    # `docs/getting-started.md` but not further nested files like
    # `docs/build-app/troubleshooting.md`.
    docs/*  @doctocat
    """)

owners.of('docs/generator/build.py')
```

I'd expect the owner to be `octocat` but the library returns `doctocat`. According to the [GitHub documentation example](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file) (and as mentioned in the comment), the single asterisk should not match nested files.

**Comment by sbdchd** [comment]
Oops! I've released a new version!

**Comment by pocmo** [comment]
Awesome, thank you! This is working for me now. :)
