### ISSUE TITLE
GitHub page isn't listed on PyPI

### ISSUE THREAD

**Issue by ngie-eign** [sbdchd/codeowners#6]
I realize this is more of a comment on the PyPI page than the github project, but the project isn't linked from the [PyPI project page](https://pypi.org/project/codeowners/).

In order to simplify collaboration and allow others to more easily audit the source, it would be good to link the GitHub project page from the PyPI page.

**Comment by sbdchd** [comment]
should be all fixed, thanks for the report!

**Comment by sbdchd** [comment]
If it wasn't fixed already, this is fixed in the latest release
